//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveSystemOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.LEAVEDATA = new HashSet<LEAVEDATA>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string identificationNo { get; set; }
        public string homeNo { get; set; }
        public string soi { get; set; }
        public string road { get; set; }
        public Nullable<int> subdistrict { get; set; }
        public Nullable<int> district { get; set; }
        public int province { get; set; }
        public string postalCode { get; set; }
        public Nullable<int> authorization_id { get; set; }
        public string password { get; set; }
        public string department { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        public virtual Provinces Provinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAVEDATA> LEAVEDATA { get; set; }
        public virtual Districts Districts { get; set; }
        public virtual Subdistricts Subdistricts { get; set; }
    }
}
