//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveSystemOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVETYPE
    {
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual LEAVEDATA LEAVEDATA { get; set; }
    }
}
